package ${package};
import com.adminpro.core.jdbc.annotation.Column;
import cn.afterturn.easypoi.excel.annotation.Excel;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.base.validator.IValidatorGroup;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.NotBlank;
import java.util.Date;
<#if parentEntity == 'BaseAuditEntity'>
import com.adminpro.framework.common.entity.BaseAuditEntity;
</#if>
<#if parentEntity == 'BaseEntity'>
import com.adminpro.core.base.entity.BaseEntity;

</#if>
<#list entityColumns as column>
    <#if column.attrType == 'Date'>
        <#break>
    </#if>
</#list>

/**
 * ${tableComment}表 ${tableName}
 *
 * @author ${author}
 * @date ${datetime}
 */
@Data
@Table(name = ${className}Entity.TABLE_NAME)
public class ${className}Entity extends ${parentEntity} {
    private static final long serialVersionUID = 1L;
    /**
    * 表名
    */
    public static final String TABLE_NAME = "${TABLENAME}";

<#list entityColumns as column>
    /**
     * ${column.columnComment}
     */
    public static final String ${column.columnNameUp} = "${column.columnNameUp}";
</#list>

<#list entityColumns as column>
    /**
     * ${column.columnComment}
     */
    <#if column.columnNameUp == primaryKey.columnNameUp>
    @AutoGeneratedKey
    @PrimaryKey
    <#else>
    @Excel(name = "${column.columnComment}")
    </#if>
    <#if column.attrType == 'String'>
    @Size(max = ${column.maxLength})
    </#if>
    <#if column.canNull == 'NO'>
        <#if column.columnNameUp == primaryKey.columnNameUp>
        @NotBlank(groups = IValidatorGroup.Update.class)
        <#else>
            <#if column.attrType == 'String'>
        @NotBlank
            <#else>
        @NotNull
            </#if>
        </#if>
    </#if>
    @Column(name=${column.columnNameUp}, type = Column.Type.${column.ATTRTYPE})
    private ${column.attrType} ${column.attrname};
</#list>
}

