package com.adminpro.rbac.domains.entity.usermenu;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 用户菜单分配表 sys_user_menu_assign_tbl
 *
 * @author simon
 * @date 2020-05-21
 */
@Data
@Table(name = UserMenuAssignEntity.TABLE_NAME)
public class UserMenuAssignEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_MENU_ASSIGN_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户域
     */
    public static final String COL_USER_DOMAIN = "COL_USER_DOMAIN";
    /**
     * 用户ID
     */
    public static final String COL_USER_ID = "COL_USER_ID";
    /**
     * 菜单名称
     */
    public static final String COL_MENU_NAME = "COL_MENU_NAME";
    /**
     * 备注
     */
    public static final String COL_REMARKS = "COL_REMARKS";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 用户域
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_DOMAIN, type = Column.Type.STRING)
    private String userDomain;
    /**
     * 用户ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;
    /**
     * 菜单名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_MENU_NAME, type = Column.Type.STRING)
    private String menuName;
    /**
     * 备注
     */
    @Size(max = 255)
    @Column(name = COL_REMARKS, type = Column.Type.STRING)
    private String remarks;

}
