package com.adminpro.system.rbac.domains.entity.domain;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * 用户域表 sys_user_domain_tbl
 *
 * @author simon
 * @date 2018-09-06
 */
@Data
@Table(name = DomainEntity.TABLE_NAME)
public class DomainEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_DOMAIN_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户域名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 用户域显示名称
     */
    public static final String COL_DISPLAY = "COL_DISPLAY";
    /**
     * 是否系统配置
     */
    public static final String COL_IS_SYSTEM = "COL_IS_SYSTEM";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 用户域名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 用户域显示名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_DISPLAY, type = Column.Type.STRING)
    private String display;
    /**
     * 是否系统配置
     */
    @Column(name = COL_IS_SYSTEM, type = Column.Type.BOOLEAN)
    private Boolean isSystem;

}
