package com.adminpro.system.rbac.domains.entity.domain;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * 用户域实体类
 * <p>
 * 该实体对应系统用户域表(SYS_USER_DOMAIN_TBL)，用于存储系统的用户域信息。
 * 用户域是多租户系统中的核心概念，用于实现数据隔离和资源划分，不同域之间的数据相互独立。
 * </p>
 * <p>
 * 主要功能包括：
 * <ul>
 * <li>域基本信息：域名称、显示名称等</li>
 * <li>系统域标识：区分系统内置域和自定义域</li>
 * <li>用户关联：用户通过userDomain字段关联到具体的域</li>
 * </ul>
 * </p>
 * <p>
 * 通过用户域可以实现：
 * <ul>
 * <li>多租户数据隔离：不同域的数据相互独立，互不干扰</li>
 * <li>权限隔离：用户只能访问所属域内的资源</li>
 * <li>资源分组：将系统资源按域进行分组管理</li>
 * </ul>
 * </p>
 * <p>
 * 继承自BaseAuditEntity，自动包含创建时间、创建人、更新时间、更新人等审计字段。
 * 使用Lombok的@Data注解自动生成getter/setter、toString、equals、hashCode等方法。
 * </p>
 *
 * @author simon
 * @date 2018-09-06
 * @see com.adminpro.framework.base.entity.BaseAuditEntity
 */
@Data
@Table(name = DomainEntity.TABLE_NAME)
public class DomainEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_DOMAIN_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户域名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 用户域显示名称
     */
    public static final String COL_DISPLAY = "COL_DISPLAY";
    /**
     * 是否系统配置
     */
    public static final String COL_IS_SYSTEM = "COL_IS_SYSTEM";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 用户域名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 用户域显示名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_DISPLAY, type = Column.Type.STRING)
    private String display;
    /**
     * 是否系统配置
     */
    @Column(name = COL_IS_SYSTEM, type = Column.Type.BOOLEAN)
    private Boolean isSystem;

}
