package com.adminpro.tools.domains.entity.job;

import com.adminpro.core.base.entity.BaseEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.Date;

/**
 * 定时任务日志表 sys_schedule_job_log_tbl
 *
 * @author simon
 * @date 2018-09-03
 */
@Data
@Table(name = ScheduleJobLogEntity.TABLE_NAME)
public class ScheduleJobLogEntity extends BaseEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_SCHEDULE_JOB_LOG_TBL";

    /**
     * 任务日志id
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 任务id
     */
    public static final String COL_JOB_ID = "COL_JOB_ID";
    /**
     * spring bean名称
     */
    public static final String COL_BEAN_NAME = "COL_BEAN_NAME";
    /**
     * 方法名
     */
    public static final String COL_METHOD_NAME = "COL_METHOD_NAME";
    /**
     * 参数
     */
    public static final String COL_PARAMS = "COL_PARAMS";
    /**
     * 任务状态    0：成功    1：失败
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 失败信息
     */
    public static final String COL_ERROR = "COL_ERROR";
    /**
     * 耗时(单位：毫秒)
     */
    public static final String COL_TIMES = "COL_TIMES";
    /**
     * 创建时间
     */
    public static final String COL_CREATED_TIME = "COL_CREATED_TIME";

    /**
     * 任务日志id
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 任务id
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_JOB_ID, type = Column.Type.STRING)
    private String jobId;
    /**
     * spring bean名称
     */
    @NotBlank
    @Size(max = 200)
    @Column(name = COL_BEAN_NAME, type = Column.Type.STRING)
    private String beanName;
    /**
     * 方法名
     */
    @NotBlank
    @Size(max = 100)
    @Column(name = COL_METHOD_NAME, type = Column.Type.STRING)
    private String methodName;
    /**
     * 参数
     */
    @Size(max = 2000)
    @Column(name = COL_PARAMS, type = Column.Type.STRING)
    private String params;
    /**
     * 任务状态    0：成功    1：失败
     */
    @Column(name = COL_STATUS, type = Column.Type.INT)
    private Integer status;
    /**
     * 失败信息
     */
    @Size(max = 2000)
    @Column(name = COL_ERROR, type = Column.Type.STRING)
    private String error;
    /**
     * 耗时(单位：毫秒)
     */
    @Column(name = COL_TIMES, type = Column.Type.INT)
    private Integer times;
    /**
     * 创建时间
     */
    @Column(name = COL_CREATED_TIME, type = Column.Type.DATETIME)
    private Date createdTime;
}
