package com.adminpro.tools.domains.entity.job;

import com.adminpro.core.base.entity.BaseEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import com.adminpro.framework.batchjob.utils.CronUtils;
import lombok.Data;
import org.apache.commons.lang3.StringUtils;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.Date;

/**
 * 定时任务表 sys_schedule_job_tbl
 *
 * @author simon
 * @date 2018-09-03
 */
@Data
@Table(name = ScheduleJobEntity.TABLE_NAME)
public class ScheduleJobEntity extends BaseEntity {

    /**
     * 任务调度参数key
     */
    public static final String JOB_PARAM_KEY = "JOB_PARAM_KEY";

    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_SCHEDULE_JOB_TBL";

    /**
     * 任务id
     */
    public static final String COL_ID = "COL_ID";
    /**
     * spring bean名称
     */
    public static final String COL_BEAN_NAME = "COL_BEAN_NAME";
    /**
     * 方法名
     */
    public static final String COL_METHOD_NAME = "COL_METHOD_NAME";
    /**
     * 参数
     */
    public static final String COL_PARAMS = "COL_PARAMS";
    /**
     * cron表达式
     */
    public static final String COL_CRON_EXPRESSION = "COL_CRON_EXPRESSION";
    /**
     * 任务状态  0：正常  1：暂停
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 备注
     */
    public static final String COL_REMARK = "COL_REMARK";
    /**
     * 创建时间
     */
    public static final String COL_CREATE_TIME = "COL_CREATED_TIME";

    /**
     * 任务id
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * spring bean名称
     */
    @NotBlank
    @Size(max = 200)
    @Column(name = COL_BEAN_NAME, type = Column.Type.STRING)
    private String beanName;
    /**
     * 方法名
     */
    @NotBlank
    @Size(max = 100)
    @Column(name = COL_METHOD_NAME, type = Column.Type.STRING)
    private String methodName;
    /**
     * 参数
     */
    @Size(max = 2000)
    @Column(name = COL_PARAMS, type = Column.Type.STRING)
    private String params;
    /**
     * cron表达式
     */
    @NotBlank
    @Size(max = 100)
    @Column(name = COL_CRON_EXPRESSION, type = Column.Type.STRING)
    private String cronExpression;
    /**
     * 任务状态  0：正常  1：暂停
     */
    @Column(name = COL_STATUS, type = Column.Type.INT)
    private Integer status;
    /**
     * 备注
     */
    @Size(max = 500)
    @Column(name = COL_REMARK, type = Column.Type.STRING)
    private String remark;
    /**
     * 创建时间
     */
    @Column(name = COL_CREATE_TIME, type = Column.Type.DATETIME)
    private Date createdTime;

    /**
     * 获取下次执行时间
     *
     * @return
     */
    public Date getNextValidTime() {
        if (StringUtils.isNotEmpty(cronExpression)) {
            return CronUtils.getNextExecution(cronExpression);
        }
        return null;
    }
}
