package com.adminpro.rbac.domains.entity.menu;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;

/**
 * 菜单权限表 sys_menu_tbl
 *
 * @author simon
 * @date 2020-05-21
 */
@Data
@Table(name = MenuEntity.TABLE_NAME)
public class MenuEntity extends BaseAuditEntity implements Comparable<MenuEntity> {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_MENU_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 菜单名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 显示名称
     */
    public static final String COL_DISPLAY = "COL_DISPLAY";
    /**
     * 显示名称
     */
    public static final String COL_PARENT_ID = "COL_PARENT_ID";
    /**
     * 显示顺序
     */
    public static final String COL_ORDER_NUM = "COL_ORDER_NUM";
    /**
     * 链接url
     */
    public static final String COL_URL = "COL_URL";
    /**
     * 是否为外链（0是 1否）
     */
    public static final String COL_IS_FRAME = "COL_IS_FRAME";
    /**
     * 菜单类型（M目录 C菜单 F按钮）
     */
    public static final String COL_TYPE = "COL_TYPE";
    /**
     * 菜单状态（0显示 1隐藏）
     */
    public static final String COL_VISIBLE = "COL_VISIBLE";
    /**
     * 菜单状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 权限标识
     */
    public static final String COL_PERMISSION = "COL_PERMISSION";
    /**
     * 图标
     */
    public static final String COL_ICON = "COL_ICON";
    /**
     * 备注
     */
    public static final String COL_REMARK = "COL_REMARK";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 菜单名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 显示名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_DISPLAY, type = Column.Type.STRING)
    private String display;
    /**
     * 显示名称
     */
    @Size(max = 128)
    @Column(name = COL_PARENT_ID, type = Column.Type.STRING)
    private String parentId;
    /**
     * 显示顺序
     */
    @NotNull(message = "不能为空")
    @Column(name = COL_ORDER_NUM, type = Column.Type.INT)
    private Integer orderNum;
    /**
     * 链接url
     */
    @Size(max = 128)
    @Column(name = COL_URL, type = Column.Type.STRING)
    private String url;
    /**
     * 是否为外链（0是 1否）
     */
    @Column(name = COL_IS_FRAME, type = Column.Type.BOOLEAN)
    private boolean frame;
    /**
     * 菜单类型（M目录 C菜单 F按钮）
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_TYPE, type = Column.Type.STRING)
    private String type;
    /**
     * 菜单状态（0显示 1隐藏）
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_VISIBLE, type = Column.Type.STRING)
    private String visible;
    /**
     * 菜单状态
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 权限标识
     */
    @Size(max = 128)
    @Column(name = COL_PERMISSION, type = Column.Type.STRING)
    private String permission;
    /**
     * 图标
     */
    @Size(max = 128)
    @Column(name = COL_ICON, type = Column.Type.STRING)
    private String icon;
    /**
     * 备注
     */
    @Size(max = 128)
    @Column(name = COL_REMARK, type = Column.Type.STRING)
    private String remark;

    private List<MenuEntity> children;

    @Override
    public int compareTo(MenuEntity m) {
        return this.getOrderNum() - m.getOrderNum();
    }
}
