package com.adminpro.rbac.domains.entity.rolemenu;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 角色和菜单关联表 sys_role_menu_assign_tbl
 *
 * @author simon
 * @date 2020-05-24
 */
@Data
@Table(name = RoleMenuAssignEntity.TABLE_NAME)
public class RoleMenuAssignEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_ROLE_MENU_ASSIGN_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 角色ID
     */
    public static final String COL_ROLE_NAME = "COL_ROLE_NAME";
    /**
     * 菜单ID
     */
    public static final String COL_MENU_NAME = "COL_MENU_NAME";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 角色名称
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_ROLE_NAME, type = Column.Type.STRING)
    private String roleName;
    /**
     * 菜单名称
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_MENU_NAME, type = Column.Type.STRING)
    private String menuName;
}
