package com.adminpro.system.rbac.domains.entity.menu;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;

/**
 * 菜单权限实体类
 * <p>
 * 该实体对应系统菜单权限表(SYS_MENU_TBL)，用于存储系统的菜单结构和权限信息。
 * 菜单是前端页面展示的基础，同时也是权限控制的载体，用于实现页面级和功能级的权限控制。
 * </p>
 * <p>
 * 主要功能包括：
 * <ul>
 * <li>菜单层级结构：通过parentId构建树形菜单结构</li>
 * <li>菜单类型管理：支持目录(M)、菜单(C)、按钮(F)三种类型</li>
 * <li>菜单显示控制：控制菜单的显示顺序、可见性、图标等</li>
 * <li>权限标识配置：配置菜单对应的权限标识，用于后端接口权限校验</li>
 * <li>外链支持：支持配置外部链接</li>
 * </ul>
 * </p>
 * <p>
 * 实现了Comparable接口，支持根据orderNum字段进行排序。
 * 继承自BaseAuditEntity，自动包含创建时间、创建人、更新时间、更新人等审计字段。
 * 使用Lombok的@Data注解自动生成getter/setter、toString、equals、hashCode等方法。
 * </p>
 *
 * @author simon
 * @date 2020-05-21
 * @see com.adminpro.framework.base.entity.BaseAuditEntity
 * @see Comparable
 */
@Data
@EqualsAndHashCode(callSuper = true)
@Table(name = MenuEntity.TABLE_NAME)
public class MenuEntity extends BaseAuditEntity implements Comparable<MenuEntity> {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_MENU_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 菜单名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 显示名称
     */
    public static final String COL_DISPLAY = "COL_DISPLAY";
    /**
     * 显示名称
     */
    public static final String COL_PARENT_ID = "COL_PARENT_ID";
    /**
     * 显示顺序
     */
    public static final String COL_ORDER_NUM = "COL_ORDER_NUM";
    /**
     * 链接url
     */
    public static final String COL_URL = "COL_URL";
    /**
     * 是否为外链（0是 1否）
     */
    public static final String COL_IS_FRAME = "COL_IS_FRAME";
    /**
     * 菜单类型（M目录 C菜单 F按钮）
     */
    public static final String COL_TYPE = "COL_TYPE";
    /**
     * 菜单状态（0显示 1隐藏）
     */
    public static final String COL_VISIBLE = "COL_VISIBLE";
    /**
     * 菜单状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 权限标识
     */
    public static final String COL_PERMISSION = "COL_PERMISSION";
    /**
     * 图标
     */
    public static final String COL_ICON = "COL_ICON";
    /**
     * 备注
     */
    public static final String COL_REMARK = "COL_REMARK";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 菜单名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 显示名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_DISPLAY, type = Column.Type.STRING)
    private String display;
    /**
     * 显示名称
     */
    @Size(max = 128)
    @Column(name = COL_PARENT_ID, type = Column.Type.STRING)
    private String parentId;
    /**
     * 显示顺序
     */
    @NotNull(message = "不能为空")
    @Column(name = COL_ORDER_NUM, type = Column.Type.INT)
    private Integer orderNum;
    /**
     * 链接url
     */
    @Size(max = 128)
    @Column(name = COL_URL, type = Column.Type.STRING)
    private String url;
    /**
     * 是否为外链（0是 1否）
     */
    @Column(name = COL_IS_FRAME, type = Column.Type.BOOLEAN)
    private boolean frame;
    /**
     * 菜单类型（M目录 C菜单 F按钮）
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_TYPE, type = Column.Type.STRING)
    private String type;
    /**
     * 菜单状态（0显示 1隐藏）
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_VISIBLE, type = Column.Type.STRING)
    private String visible;
    /**
     * 菜单状态
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 权限标识
     */
    @Size(max = 128)
    @Column(name = COL_PERMISSION, type = Column.Type.STRING)
    private String permission;
    /**
     * 图标
     */
    @Size(max = 128)
    @Column(name = COL_ICON, type = Column.Type.STRING)
    private String icon;
    /**
     * 备注
     */
    @Size(max = 128)
    @Column(name = COL_REMARK, type = Column.Type.STRING)
    private String remark;

    /**
     * 子菜单列表
     * <p>
     * 用于构建树形菜单结构，包含当前菜单的所有直接子菜单。
     * 该字段不在数据库中存储，仅在运行时用于构建菜单树。
     * </p>
     */
    private List<MenuEntity> children;

    /**
     * 比较两个菜单的排序顺序
     * <p>
     * 根据orderNum字段进行比较，用于菜单列表的排序。
     * </p>
     *
     * @param m 要比较的菜单对象
     * @return 如果当前菜单的orderNum小于参数菜单的orderNum，返回负数；相等返回0；否则返回正数
     */
    @Override
    public int compareTo(MenuEntity m) {
        return this.getOrderNum() - m.getOrderNum();
    }
}
