package com.adminpro.rbac.domains.entity.notification;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.Date;

/**
 * 通知表 sys_notification_tbl
 *
 * @author simon
 * @date 2018-09-25
 */
@Data
@Table(name = NotificationEntity.TABLE_NAME)
public class NotificationEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_NOTIFICATION_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 标题
     */
    public static final String COL_TITLE = "COL_TITLE";
    /**
     * 内容
     */
    public static final String COL_CONTENT = "COL_CONTENT";
    /**
     * 用户域
     */
    public static final String COL_USER_DOMAIN = "COL_USER_DOMAIN";
    /**
     * 开始时间
     */
    public static final String COL_START_TIME = "COL_START_TIME";
    /**
     * 结束时间
     */
    public static final String COL_END_TIME = "COL_END_TIME";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 标题
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_TITLE, type = Column.Type.STRING)
    private String title;
    /**
     * 内容
     */
    private String content;
    /**
     * 用户域
     */
    private String userDomain;
    /**
     * 开始时间
     */
    private Date startTime;
    /**
     * 结束时间
     */
    private Date endTime;

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return content;
    }

    public void setUserDomain(String userDomain) {
        this.userDomain = userDomain;
    }

    public String getUserDomain() {
        return userDomain;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getEndTime() {
        return endTime;
    }


    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
                .append("id", getId())
                .append("title", getTitle())
                .append("content", getContent())
                .append("userDomain", getUserDomain())
                .append("startTime", getStartTime())
                .append("endTime", getEndTime())
                .append("createdByUserDomain", getCreatedByUserDomain())
                .append("createdByUserId", getCreatedByUserId())
                .append("createdDate", getCreatedDate())
                .append("updatedByUserDomain", getUpdatedByUserDomain())
                .append("updatedByUserId", getUpdatedByUserId())
                .append("updatedDate", getUpdatedDate())
                .toString();
    }
}
