package com.adminpro.tools.domains.entity.session;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 用户Session表 sys_session_tbl
 *
 * @author simon
 * @date 2020-06-17
 */
@Data
@Table(name = SessionEntity.TABLE_NAME)
public class SessionEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_SESSION_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * Session ID
     */
    public static final String COL_SESSION_ID = "COL_SESSION_ID";
    /**
     * 第三方Session ID
     */
    public static final String COL_THIRD_PARTY_SESSION_ID = "COL_THIRD_PARTY_SESSION_ID";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 用户域
     */
    public static final String COL_USER_DOMAIN = "COL_USER_DOMAIN";
    /**
     * 用户ID
     */
    public static final String COL_USER_ID = "COL_USER_ID";
    /**
     * 用户登录名
     */
    public static final String COL_LOGIN_NAME = "COL_LOGIN_NAME";
    /**
     * 登陆IP
     */
    public static final String COL_IP_ADDR = "COL_IP_ADDR";
    /**
     * 登陆地址
     */
    public static final String COL_LOGIN_LOCATION = "COL_LOGIN_LOCATION";
    /**
     * 浏览器
     */
    public static final String COL_BROWSER = "COL_BROWSER";
    /**
     * 操作系统
     */
    public static final String COL_OS = "COL_OS";
    /**
     * 部门编号
     */
    public static final String COL_DEPT_NO = "COL_DEPT_NO";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * Session ID
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_SESSION_ID, type = Column.Type.STRING)
    private String sessionId;
    /**
     * 第三方Session ID
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_THIRD_PARTY_SESSION_ID, type = Column.Type.STRING)
    private String thirdPartySessionId;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 用户域
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_DOMAIN, type = Column.Type.STRING)
    private String userDomain;
    /**
     * 用户ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;
    /**
     * 登陆名
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_LOGIN_NAME, type = Column.Type.STRING)
    private String loginName;
    /**
     * 登陆IP
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_IP_ADDR, type = Column.Type.STRING)
    private String ipAddr;
    /**
     * 登陆地址
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_LOGIN_LOCATION, type = Column.Type.STRING)
    private String loginLocation;
    /**
     * 浏览器
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_BROWSER, type = Column.Type.STRING)
    private String browser;
    /**
     * 操作系统
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_OS, type = Column.Type.STRING)
    private String os;
    /**
     * 部门编号
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_DEPT_NO, type = Column.Type.STRING)
    private String deptNo;
}
