package com.adminpro.rbac.domains.entity.apk;

import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import com.adminpro.framework.common.entity.BaseAuditEntity;
import lombok.Data;

import jakarta.validation.constraints.Size;

/**
 * APK版本管理表 sys_apk_tbl
 *
 * @author simon
 * @date 2021-02-03
 */
@Data
@Table(name = APKEntity.TABLE_NAME)
public class APKEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_APK_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * APK类型
     */
    public static final String COL_TYPE = "COL_TYPE";
    /**
     * 是否强制更新
     */
    public static final String COL_FORCE_UPDATE = "COL_FORCE_UPDATE";
    /**
     * Version名称
     */
    public static final String COL_VER_NAME = "COL_VER_NAME";
    /**
     * Version Code
     */
    public static final String COL_VER_CODE = "COL_VER_CODE";
    /**
     * 系统版本
     */
    public static final String COL_OS_VERSION = "COL_OS_VERSION";
    /**
     * 下载地址
     */
    public static final String COL_DOWNLOAD_URL = "COL_DOWNLOAD_URL";
    /**
     * 升级说明
     */
    public static final String COL_MESSAGE = "COL_MESSAGE";

    /**
     * ID
     */
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * APK类型
     */
    @Size(max = 64)
    @Column(name = COL_TYPE, type = Column.Type.STRING)
    private String type;
    /**
     * 是否强制更新
     */
    @Column(name = COL_FORCE_UPDATE, type = Column.Type.BOOLEAN)
    private boolean forceUpdate;
    /**
     * Version名称
     */
    @Size(max = 64)
    @Column(name = COL_VER_NAME, type = Column.Type.STRING)
    private String verName;
    /**
     * Version Code
     */
    @Column(name = COL_VER_CODE, type = Column.Type.INT)
    private Integer verCode;
    /**
     * 系统版本
     */
    @Size(max = 64)
    @Column(name = COL_OS_VERSION, type = Column.Type.STRING)
    private String osVersion;
    /**
     * 下载地址
     */
    @Size(max = 255)
    @Column(name = COL_DOWNLOAD_URL, type = Column.Type.STRING)
    private String downloadUrl;
    /**
     * 升级说明
     */
    @Column(name = COL_MESSAGE, type = Column.Type.STRING)
    private String message;
}
