package com.adminpro.rbac.domains.entity.usertoken;

import com.adminpro.core.base.entity.BaseEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import org.apache.commons.lang3.StringUtils;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.Date;


/**
 * 用户Token表 sys_user_token_tbl
 *
 * @author simon
 * @date 2018-09-03
 */
@Data
@Table(name = UserTokenEntity.TABLE_NAME)
public class UserTokenEntity extends BaseEntity {

    public static final String STATUS_ACTIVITY = "activity";
    public static final String STATUS_INACTIVITY = "inactivity";

    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_TOKEN_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * Token值
     */
    public static final String COL_TOKEN = "COL_TOKEN";
    /**
     * 用户域
     */
    public static final String COL_USER_DOMAIN = "COL_USER_DOMAIN";
    /**
     * 用户ID
     */
    public static final String COL_USER_ID = "COL_USER_ID";
    /**
     * 登录名
     */
    public static final String COL_LOGIN_NAME = "COL_LOGIN_NAME";
    /**
     * 登录设备
     */
    public static final String COL_DEVICE = "COL_DEVICE";
    /**
     * 过期时间
     */
    public static final String COL_EXPIRE_TIME = "COL_EXPIRE_TIME";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 更新时间
     */
    public static final String COL_UPDATE_TIME = "COL_UPDATE_TIME";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * Token值
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_TOKEN, type = Column.Type.STRING)
    private String token;
    /**
     * 用户域
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_DOMAIN, type = Column.Type.STRING)
    private String userDomain;
    /**
     * 用户ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;
    /**
     * 登录名
     */
    @Size(max = 255)
    @Column(name = COL_LOGIN_NAME, type = Column.Type.STRING)
    private String loginName;
    /**
     * 登录设备
     */
    @Size(max = 255)
    @Column(name = COL_DEVICE, type = Column.Type.STRING)
    private String device;
    /**
     * 过期时间
     */
    @Column(name = COL_EXPIRE_TIME, type = Column.Type.DATETIME)
    private Date expireTime;
    /**
     * 状态
     */
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 更新时间
     */
    @Column(name = COL_UPDATE_TIME, type = Column.Type.DATETIME)
    private Date updateTime;


    @JsonIgnore
    public boolean isValid() {
        return StringUtils.equals(getStatus(), STATUS_ACTIVITY) && !expireTime.before(new Date());
    }
}
