package com.adminpro.system.rbac.domains.entity.role;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.List;

/**
 * 角色实体类
 * <p>
 * 该实体对应系统角色表(SYS_ROLE_TBL)，用于存储RBAC（基于角色的访问控制）系统中的角色信息。
 * 角色是权限管理的重要概念，用于将权限分配给用户，实现用户与权限的解耦。
 * </p>
 * <p>
 * 主要功能包括：
 * <ul>
 * <li>角色基本信息：角色名称、显示名称等</li>
 * <li>角色状态管理：启用/禁用状态</li>
 * <li>系统角色标识：区分系统内置角色和自定义角色</li>
 * <li>菜单权限关联：通过menuIds字段关联该角色拥有的菜单权限</li>
 * </ul>
 * </p>
 * <p>
 * 继承自BaseAuditEntity，自动包含创建时间、创建人、更新时间、更新人等审计字段。
 * 使用Lombok的@Data注解自动生成getter/setter、toString、equals、hashCode等方法。
 * </p>
 *
 * @author simon
 * @date 2018-09-06
 * @see com.adminpro.framework.base.entity.BaseAuditEntity
 */
@Data
@EqualsAndHashCode(callSuper = true)
@Table(name = RoleEntity.TABLE_NAME)
public class RoleEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_ROLE_TBL";

    /**
     * 角色ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 角色名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 角色显示名称
     */
    public static final String COL_DISPLAY = "COL_DISPLAY";
    /**
     * 是否系统配置
     */
    public static final String COL_IS_SYSTEM = "COL_IS_SYSTEM";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";

    /**
     * 角色ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 角色名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 角色显示名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_DISPLAY, type = Column.Type.STRING)
    private String display;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 是否系统配置
     */
    @Column(name = COL_IS_SYSTEM, type = Column.Type.BOOLEAN)
    private boolean system;

    /**
     * 该角色关联的菜单ID列表
     * <p>
     * 用于构建角色与菜单的多对多关联关系，表示该角色拥有的菜单权限。
     * 在角色权限分配时，通过此字段设置角色可访问的菜单资源。
     * </p>
     */
    private List<String> menuIds;
}
