package com.adminpro.system.rbac.domains.entity.userpost;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * 用户角色分配表 sys_user_post_assign_tbl
 *
 * @author simon
 * @date 2020-06-14
 */
@Data
@Table(name = UserPostAssignEntity.TABLE_NAME)
public class UserPostAssignEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_POST_ASSIGN_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户ID
     */
    public static final String COL_USER_ID = "COL_USER_ID";
    /**
     * 职位ID
     */
    public static final String COL_POST_ID = "COL_POST_ID";
    /**
     * 备注
     */
    public static final String COL_REMARKS = "COL_REMARKS";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 用户ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;
    /**
     * 职位ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_POST_ID, type = Column.Type.STRING)
    private String postId;
    /**
     * 备注
     */
    @Size(max = 255)
    @Column(name = COL_REMARKS, type = Column.Type.STRING)
    private String remarks;

}
