package com.adminpro.system.rbac.domains.entity.user;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import java.util.Date;

/**
 * 用户表 sys_user_tbl
 *
 * @author simon
 * @date 2020-05-21
 */
@Data
@Table(name = UserEntity.TABLE_NAME)
public class UserEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户域
     */
    public static final String COL_USER_DOMAIN = "COL_USER_DOMAIN";
    /**
     * 用户登录名称
     */
    public static final String COL_LOGIN_NAME = "COL_LOGIN_NAME";
    /**
     * 用户显示昵称
     */
    public static final String COL_DISPLAY = "COL_DISPLAY";
    /**
     * 用户真实名称
     */
    public static final String COL_REAL_NAME = "COL_REAL_NAME";
    /**
     * 用户身份证号
     */
    public static final String COL_ID_NO = "COL_ID_NO";
    /**
     * 用户邮箱
     */
    public static final String COL_EMAIL = "COL_EMAIL";
    /**
     * 用户状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 是否实名认证
     */
    public static final String COL_AUTHENTICATED = "COL_AUTHENTICATED";
    /**
     * 手机号码
     */
    public static final String COL_MOBILE_NO = "COL_MOBILE_NO";
    /**
     * 是否系统配置
     */
    public static final String COL_IS_SYSTEM = "COL_IS_SYSTEM";
    /**
     * 地址
     */
    public static final String COL_ADDRESS = "COL_ADDRESS";
    /**
     * 密码
     */
    public static final String COL_PWD = "COL_PWD";
    /**
     * 生日
     */
    public static final String COL_BIRTHDAY = "COL_BIRTHDAY";
    /**
     * 性别
     */
    public static final String COL_SEX = "COL_SEX";
    /**
     * 婚姻状态
     */
    public static final String COL_MARITAL = "COL_MARITAL";
    /**
     * 民族
     */
    public static final String COL_NATION = "COL_NATION";
    /**
     * 是否免密支付
     */
    public static final String COL_PAY_NO_PWD = "COL_PAY_NO_PWD";
    /**
     * 支付密码
     */
    public static final String COL_PAY_PWD = "COL_PAY_PWD";
    /**
     * 免密支付阀值
     */
    public static final String COL_PAY_NO_PWD_POINT = "COL_PAY_NO_PWD_POINT";
    /**
     * 头像地址
     */
    public static final String COL_AVATAR_URL = "COL_AVATAR_URL";
    /**
     * 职位
     */
    public static final String COL_POST = "COL_POST";
    /**
     * 职业
     */
    public static final String COL_PROFESSION = "COL_PROFESSION";
    /**
     * 星座
     */
    public static final String COL_CONSTELLATION = "COL_CONSTELLATION";
    /**
     * 第三方账号
     */
    public static final String COL_THIRD_PARTY_USER_NAME = "COL_THIRD_PARTY_USER_NAME";
    /**
     * 第三方密码
     */
    public static final String COL_THIRD_PARTY_PWD = "COL_THIRD_PARTY_PWD";
    /**
     * 工号
     */
    public static final String COL_JOB_NO = "COL_JOB_NO";
    /**
     * 外部用户ID
     */
    public static final String COL_EXT_USER_ID = "COL_EXT_USER_ID";
    /**
     * 实名认证时间
     */
    public static final String COL_AUTHENTICATE_DATE = "COL_AUTHENTICATE_DATE";
    /**
     * 最后登录时间
     */
    public static final String COL_LATEST_LOGIN_TIME = "COL_LATEST_LOGIN_TIME";
    /**
     * 最后修改支付密码时间
     */
    public static final String COL_LATEST_CHANGE_PWD_TIME = "COL_LATEST_CHANGE_PWD_TIME";
    /**
     * 用户描述
     */
    public static final String COL_DESCRIPTION = "COL_DESCRIPTION";
    /**
     * 部门号
     */
    public static final String COL_DEPT_NO = "COL_DEPT_NO";
    /**
     * 分享码
     */
    public static final String COL_SHARE_CODE = "COL_SHARE_CODE";
    /**
     * 上级分享码
     */
    public static final String COL_PARENT_SHARE_CODE = "COL_PARENT_SHARE_CODE";
    /**
     * 用户积分
     */
    public static final String COL_INTEGRAL = "COL_INTEGRAL";
    /**
     * 省
     */
    public static final String COL_PROVINCE = "COL_PROVINCE";
    /**
     * 市
     */
    public static final String COL_CITY = "COL_CITY";
    /**
     * 区
     */
    public static final String COL_DISTRICT = "COL_DISTRICT";

    /**
     * 用户域
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_DOMAIN, type = Column.Type.STRING)
    private String userDomain;
    /**
     * 用户登录名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_LOGIN_NAME, type = Column.Type.STRING)
    private String loginName;
    /**
     * 用户显示昵称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_DISPLAY, type = Column.Type.STRING)
    private String display;
    /**
     * 用户真实名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_REAL_NAME, type = Column.Type.STRING)
    private String realName;
    /**
     * 用户身份证号
     */
    @Size(max = 255)
    @Column(name = COL_ID_NO, type = Column.Type.STRING)
    private String idNo;
    /**
     * 用户邮箱
     */
    @Email
    @Size(max = 255)
    @Column(name = COL_EMAIL, type = Column.Type.STRING)
    private String email;
    /**
     * 用户状态
     */
    @Size(max = 11)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 是否实名认证
     */
    @Column(name = COL_AUTHENTICATED, type = Column.Type.BOOLEAN)
    private boolean authenticated;
    /**
     * 手机号码
     */
    @Size(max = 255)
    @Column(name = COL_MOBILE_NO, type = Column.Type.STRING)
    private String mobileNo;
    /**
     * 是否系统配置
     */
    @Column(name = COL_IS_SYSTEM, type = Column.Type.BOOLEAN)
    private boolean system;
    /**
     * 地址
     */
    @Size(max = 255)
    @Column(name = COL_ADDRESS, type = Column.Type.STRING)
    private String address;
    /**
     * 密码
     */
    @Column(name = COL_PWD, type = Column.Type.STRING)
    private String password;
    /**
     * 生日
     */
    @Column(name = COL_BIRTHDAY, type = Column.Type.DATETIME)
    private Date birthday;
    /**
     * 性别
     */
    @Size(max = 12)
    @Column(name = COL_SEX, type = Column.Type.STRING)
    private String sex;
    /**
     * 婚姻状态
     */
    @Size(max = 12)
    @Column(name = COL_MARITAL, type = Column.Type.STRING)
    private String marital;
    /**
     * 民族
     */
    @Size(max = 255)
    @Column(name = COL_NATION, type = Column.Type.STRING)
    private String nation;
    /**
     * 是否免密支付
     */
    @Column(name = COL_PAY_NO_PWD, type = Column.Type.BOOLEAN)
    private boolean payNoPwd;
    /**
     * 支付密码
     */
    @Column(name = COL_PAY_PWD, type = Column.Type.STRING)
    private String payPwd;
    /**
     * 免密支付阀值
     */
    @Column(name = COL_PAY_NO_PWD_POINT, type = Column.Type.INT)
    private Integer payNoPwdPoint;
    /**
     * 头像地址
     */
    @Size(max = 255)
    @Column(name = COL_AVATAR_URL, type = Column.Type.STRING)
    private String avatarUrl;
    /**
     * 职位
     */
    @Size(max = 255)
    @Column(name = COL_POST, type = Column.Type.STRING)
    private String post;
    /**
     * 职业
     */
    @Size(max = 255)
    @Column(name = COL_PROFESSION, type = Column.Type.STRING)
    private String profession;
    /**
     * 星座
     */
    @Size(max = 255)
    @Column(name = COL_CONSTELLATION, type = Column.Type.STRING)
    private String constellation;
    /**
     * 第三方账号
     */
    @Size(max = 255)
    @Column(name = COL_THIRD_PARTY_USER_NAME, type = Column.Type.STRING)
    private String thirdPartyUserName;
    /**
     * 第三方密码
     */
    @Size(max = 255)
    @Column(name = COL_THIRD_PARTY_PWD, type = Column.Type.STRING)
    private String thirdPartyPwd;
    /**
     * 工号
     */
    @Size(max = 255)
    @Column(name = COL_JOB_NO, type = Column.Type.STRING)
    private String jobNo;
    /**
     * 外部用户ID
     */
    @Size(max = 255)
    @Column(name = COL_EXT_USER_ID, type = Column.Type.STRING)
    private String extUserId;
    /**
     * 实名认证时间
     */
    @Column(name = COL_AUTHENTICATE_DATE, type = Column.Type.DATETIME)
    private Date authenticateDate;
    /**
     * 最后登录时间
     */
    @Column(name = COL_LATEST_LOGIN_TIME, type = Column.Type.DATETIME)
    private Date latestLoginTime;
    /**
     * 最后修改支付密码时间
     */
    @Column(name = COL_LATEST_CHANGE_PWD_TIME, type = Column.Type.DATETIME)
    private Date latestChangePwdTime;
    /**
     * 个人简介
     */
    @Size(max = 255)
    @Column(name = COL_DESCRIPTION, type = Column.Type.STRING)
    private String description;
    /**
     * 部门号
     */
    @Size(max = 255)
    @Column(name = COL_DEPT_NO, type = Column.Type.STRING)
    private String deptNo;
    /**
     * 分享码
     */
    @Size(max = 255)
    @Column(name = COL_SHARE_CODE, type = Column.Type.STRING)
    private String shareCode;
    /**
     * 上级分享码
     */
    @Size(max = 255)
    @Column(name = COL_PARENT_SHARE_CODE, type = Column.Type.STRING)
    private String parentShareCode;
    /**
     * 用户积分
     */
    @Column(name = COL_INTEGRAL, type = Column.Type.LONG)
    private Long integral;
    /**
     * 省
     */
    @Size(max = 64)
    @Column(name = COL_PROVINCE, type = Column.Type.STRING)
    private String province;
    /**
     * 市
     */
    @Size(max = 64)
    @Column(name = COL_CITY, type = Column.Type.STRING)
    private String city;
    /**
     * 区
     */
    @Size(max = 64)
    @Column(name = COL_DISTRICT, type = Column.Type.STRING)
    private String district;

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
                .append("id", getId())
                .append("userDomain", getUserDomain())
                .append("loginName", getLoginName())
                .append("display", getDisplay())
                .append("realName", getRealName())
                .append("idNo", getIdNo())
                .append("email", getEmail())
                .append("status", getStatus())
                .append("authenticated", isAuthenticated())
                .append("mobileNo", getMobileNo())
                .append("isSystem", isSystem())
                .append("address", getAddress())
                .append("pwd", getPassword())
                .append("birthday", getBirthday())
                .append("sex", getSex())
                .append("marital", getMarital())
                .append("nation", getNation())
                .append("payNoPwd", isPayNoPwd())
                .append("payPwd", getPayPwd())
                .append("payNoPwdPoint", getPayNoPwdPoint())
                .append("avatarUrl", getAvatarUrl())
                .append("post", getPost())
                .append("profession", getProfession())
                .append("constellation", getConstellation())
                .append("thirdPartyUserName", getThirdPartyUserName())
                .append("thirdPartyPwd", getThirdPartyPwd())
                .append("jobNo", getJobNo())
                .append("extUserId", getExtUserId())
                .append("authenticateDate", getAuthenticateDate())
                .append("latestLoginTime", getLatestLoginTime())
                .append("latestChangePwdTime", getLatestChangePwdTime())
                .append("description", getDescription())
                .append("deptNo", getDeptNo())
                .append("shareCode", getShareCode())
                .append("parentShareCode", getParentShareCode())
                .append("integral", getIntegral())
                .append("province", getProvince())
                .append("city", getCity())
                .append("district", getDistrict())
                .append("createdAt", getCreatedAt())
                .append("createdBy", getCreatedBy())
                .append("updatedAt", getUpdatedAt())
                .append("updatedBy", getUpdatedBy())
                .toString();
    }
}
