package com.adminpro.system.rbac.domains.entity.user;

import com.adminpro.framework.base.entity.BaseEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * 用户标签表 sys_user_tag_tbl
 *
 * @author simon
 * @date 2020-05-21
 */
@Data
@Table(name = UserTagEntity.TABLE_NAME)
public class UserTagEntity extends BaseEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_TAG_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户ID
     */
    public static final String COL_USER_ID = "COL_USER_ID";
    /**
     * 标签内容
     */
    public static final String COL_TAG = "COL_TAG";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 用户ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;
    /**
     * 标签内容
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_TAG, type = Column.Type.STRING)
    private String tag;

}
