package com.adminpro.rbac.domains.entity.role;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.List;

/**
 * 角色表 sys_role_tbl
 *
 * @author simon
 * @date 2018-09-06
 */
@Data
@Table(name = RoleEntity.TABLE_NAME)
public class RoleEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_ROLE_TBL";

    /**
     * 角色ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 角色名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 角色显示名称
     */
    public static final String COL_DISPLAY = "COL_DISPLAY";
    /**
     * 是否系统配置
     */
    public static final String COL_IS_SYSTEM = "COL_IS_SYSTEM";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";

    /**
     * 角色ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 角色名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 角色显示名称
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_DISPLAY, type = Column.Type.STRING)
    private String display;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 是否系统配置
     */
    @Column(name = COL_IS_SYSTEM, type = Column.Type.BOOLEAN)
    private boolean system;

    private List<String> menuNames;
}
