package com.adminpro.system.rbac.domains.entity.post;

import com.adminpro.framework.base.entity.BaseAuditEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * 职位实体类
 * <p>
 * 该实体对应系统职位表(SYS_POST_TBL)，用于存储组织中的职位信息。
 * 职位是组织架构中的重要概念，用于定义员工的工作岗位和职责，通常与部门和角色关联使用。
 * </p>
 * <p>
 * 主要功能包括：
 * <ul>
 * <li>职位基本信息：职位编码、职位名称等</li>
 * <li>职位显示控制：通过sort字段控制职位的显示顺序</li>
 * <li>职位状态管理：启用/禁用状态</li>
 * <li>职位描述：通过remark字段记录职位的详细说明</li>
 * </ul>
 * </p>
 * <p>
 * 继承自BaseAuditEntity，自动包含创建时间、创建人、更新时间、更新人等审计字段。
 * 使用Lombok的@Data注解自动生成getter/setter、toString、equals、hashCode等方法。
 * </p>
 *
 * @author simon
 * @date 2020-05-21
 * @see com.adminpro.framework.base.entity.BaseAuditEntity
 */
@Data
@Table(name = PostEntity.TABLE_NAME)
public class PostEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_POST_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 职位编码
     */
    public static final String COL_CODE = "COL_CODE";
    /**
     * 职位名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 显示顺序
     */
    public static final String COL_SORT = "COL_SORT";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 备注
     */
    public static final String COL_REMARK = "COL_REMARK";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 职位编码
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_CODE, type = Column.Type.STRING)
    private String code;
    /**
     * 职位名称
     */
    @NotBlank
    @Size(max = 50)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 显示顺序
     */
    @Column(name = COL_SORT, type = Column.Type.INT)
    private Integer sort;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 20)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 备注
     */
    @Size(max = 500)
    @Column(name = COL_REMARK, type = Column.Type.STRING)
    private String remark;
}
