package com.adminpro.tools.domains.entity.syslog;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 系统日志表 sys_sys_log_tbl
 *
 * @author simon
 * @date 2018-11-29
 */
@Data
@Table(name = SysLogEntity.TABLE_NAME)
public class SysLogEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_SYS_LOG_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户域
     */
    public static final String COL_USER_DOMAIN = "COL_USER_DOMAIN";
    /**
     * 用户ID
     */
    public static final String COL_USER_ID = "COL_USER_ID";
    /**
     * 用户IP
     */
    public static final String COL_IP = "COL_IP";
    /**
     * 浏览器
     */
    public static final String COL_BROWSER = "COL_BROWSER";
    /**
     * 访问Request Method
     */
    public static final String COL_METHOD = "COL_METHOD";
    /**
     * 操作系统
     */
    public static final String COL_OS = "COL_OS";
    /**
     * 操作描述
     */
    public static final String COL_DESCRIPTION = "COL_DESCRIPTION";
    /**
     * 访问参数
     */
    public static final String COL_PARAMS = "COL_PARAMS";
    /**
     * Response
     */
    public static final String COL_RESPONSE = "COL_RESPONSE";
    /**
     * 消耗时间
     */
    public static final String COL_TIME = "COL_TIME";
    /**
     * 分类
     */
    public static final String COL_CATEGORY = "COL_CATEGORY";
    /**
     * 模块
     */
    public static final String COL_MODULE = "COL_MODULE";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 用户域
     */
    @Size(max = 64)
    @Column(name = COL_USER_DOMAIN, type = Column.Type.STRING)
    private String userDomain;
    /**
     * 用户ID
     */
    @Size(max = 64)
    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;
    /**
     * 用户IP
     */
    @Size(max = 255)
    @Column(name = COL_IP, type = Column.Type.STRING)
    private String ip;
    /**
     * 浏览器
     */
    @Size(max = 255)
    @Column(name = COL_BROWSER, type = Column.Type.STRING)
    private String browser;
    /**
     * 访问Request Method
     */
    @Size(max = 255)
    @Column(name = COL_METHOD, type = Column.Type.STRING)
    private String method;
    /**
     * 操作系统
     */
    @Size(max = 255)
    @Column(name = COL_OS, type = Column.Type.STRING)
    private String os;
    /**
     * 操作描述
     */
    @Size(max = 255)
    @Column(name = COL_DESCRIPTION, type = Column.Type.STRING)
    private String description;
    /**
     * 访问参数
     */
    @Column(name = COL_PARAMS, type = Column.Type.STRING)
    private String params;
    /**
     * Response
     */
    @Column(name = COL_RESPONSE, type = Column.Type.STRING)
    private String response;
    /**
     * 消耗时间
     */
    @Column(name = COL_TIME, type = Column.Type.LONG)
    private Long time;
    /**
     * 分类
     */
    @Size(max = 64)
    @Column(name = COL_CATEGORY, type = Column.Type.STRING)
    private String category;
    /**
     * 模块
     */
    @Size(max = 64)
    @Column(name = COL_MODULE, type = Column.Type.STRING)
    private String module;
    /**
     * 状态
     */
    @Size(max = 32)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
}
