package com.adminpro.rbac.domains.entity.dept;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;

/**
 * 部门表 sys_dept_tbl
 *
 * @author simon
 * @date 2020-05-24
 */
@Data
@Table(name = DeptEntity.TABLE_NAME)
public class DeptEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_DEPT_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 部门编号
     */
    public static final String COL_NO = "COL_NO";
    /**
     * ID
     */
    public static final String COL_PARENT_ID = "COL_PARENT_ID";
    /**
     * 祖级列表
     */
    public static final String COL_ANCESTORS = "COL_ANCESTORS";
    /**
     * 部门名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 显示顺序
     */
    public static final String COL_ORDER_NUM = "COL_ORDER_NUM";
    /**
     * 删除标志（0代表存在 2代表删除）
     */
    public static final String COL_DEL_FLAG = "COL_DEL_FLAG";
    /**
     * 部门描述
     */
    public static final String COL_DESCRIPTION = "COL_DESCRIPTION";
    /**
     * 联系人
     */
    public static final String COL_LINKMAN = "COL_LINKMAN";
    /**
     * 联系方式
     */
    public static final String COL_CONTACT = "COL_CONTACT";
    /**
     * 联系电话
     */
    public static final String COL_PHONE = "COL_PHONE";
    /**
     * 邮箱
     */
    public static final String COL_EMAIL = "COL_EMAIL";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 部门图标
     */
    public static final String COL_LOGO_PATH = "COL_LOGO_PATH";

    public static final String COL_CUSTOM_LOGIN = "COL_CUSTOM_LOGIN";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 部门编号
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NO, type = Column.Type.STRING)
    private String no;
    /**
     * ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_PARENT_ID, type = Column.Type.STRING)
    private String parentId;
    /**
     * 祖级列表
     */
    @Size(max = 64)
    @Column(name = COL_ANCESTORS, type = Column.Type.STRING)
    private String ancestors;
    /**
     * 部门名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 显示顺序
     */
    @NotNull(message = "不能为空")
    @Column(name = COL_ORDER_NUM, type = Column.Type.INT)
    private Integer orderNum;
    /**
     * 删除标志（0代表存在 2代表删除）
     */
    @Column(name = COL_DEL_FLAG, type = Column.Type.INT)
    private Integer delFlag;
    /**
     * 部门描述
     */
    @Size(max = 255)
    @Column(name = COL_DESCRIPTION, type = Column.Type.STRING)
    private String description;
    /**
     * 联系人
     */
    @Size(max = 128)
    @Column(name = COL_LINKMAN, type = Column.Type.STRING)
    private String linkman;
    /**
     * 联系方式
     */
    @Size(max = 128)
    @Column(name = COL_CONTACT, type = Column.Type.STRING)
    private String contact;
    /**
     * 联系电话
     */
    @Size(max = 128)
    @Column(name = COL_PHONE, type = Column.Type.STRING)
    private String phone;
    /**
     * 邮箱
     */
    @Email
    @Size(max = 128)
    @Column(name = COL_EMAIL, type = Column.Type.STRING)
    private String email;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;

    @Column(name = COL_LOGO_PATH, type = Column.Type.STRING)
    private String logoPath;

    @Column(name = COL_CUSTOM_LOGIN, type = Column.Type.BOOLEAN)
    private boolean customLogin;

    private List<DeptEntity> children;

}
