package com.adminpro.tools.domains.entity.auditlog;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.Size;
import java.util.Date;

/**
 * 日志类
 *
 * @author simon
 */
@Data
@Table(name = AuditLogEntity.TABLE_NAME)
public class AuditLogEntity extends BaseAuditEntity {

    private static final long serialVersionUID = 1L;

    public static final String TABLE_NAME = "SYS_AUDIT_LOG_TBL";

    public static final String COL_ID = "COL_ID";

    public static final String COL_LOG_DATE = "COL_LOG_DATE";

    public static final String COL_CATEGORY = "COL_CATEGORY";

    public static final String COL_MODULE = "COL_MODULE";

    public static final String COL_BEFORE_DATA = "COL_BEFORE_DATA";
    public static final String COL_AFTER_DATA = "COL_AFTER_DATA";

    public static final String COL_IP_ADDRESS = "COL_IP_ADDRESS";

    public static final String COL_STATUS = "COL_STATUS";

    public static final String COL_EVENT = "COL_EVENT";

    public static final String COL_SESSION_ID = "COL_SESSION_ID";

    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;

    @Column(name = COL_LOG_DATE, type = Column.Type.DATETIME)
    private Date logDate;

    @Column(name = COL_CATEGORY, type = Column.Type.STRING)
    private String category;

    @Column(name = COL_MODULE, type = Column.Type.STRING)
    private String module;

    @Column(name = COL_BEFORE_DATA, type = Column.Type.STRING)
    private String beforeData;

    @Column(name = COL_AFTER_DATA, type = Column.Type.STRING)
    private String afterData;

    @Column(name = COL_IP_ADDRESS, type = Column.Type.STRING)
    private String ipAddress;

    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;

    @Column(name = COL_EVENT, type = Column.Type.STRING)
    private String event;

    @Column(name = COL_SESSION_ID, type = Column.Type.STRING)
    private String sessionId;

}
