package com.adminpro.tools.domains.entity.exceptionlog;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 异常表 sys_exception_log
 *
 * @author simon
 * @date 2018-11-29
 */
@Data
@Table(name = ExceptionLogEntity.TABLE_NAME)
public class ExceptionLogEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_EXCEPTION_LOG";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 异常类型
     */
    public static final String COL_TYPE = "COL_TYPE";
    /**
     * 异常详情
     */
    public static final String COL_DETAILS = "COL_DETAILS";
    /**
     * 路径
     */
    public static final String COL_PATH = "COL_PATH";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 异常类型
     */
    @NotBlank
    @Column(name = COL_TYPE, type = Column.Type.STRING)
    private String type;
    /**
     * 路径
     */
    @Size(max = 255)
    @Column(name = COL_PATH, type = Column.Type.STRING)
    private String path;
    /**
     * 异常详情
     */
    @NotBlank
    @Column(name = COL_DETAILS, type = Column.Type.STRING)
    private String details;

}
