package com.adminpro.rbac.domains.entity.city;

import com.adminpro.core.base.entity.BaseEntity;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.Size;

/**
 * 城市区划表 sys_city_tbl
 *
 * @author simon
 * @date 2018-09-06
 */
@Data
@Table(name = CityEntity.TABLE_NAME)
public class CityEntity extends BaseEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_CITY_TBL";

    /**
     * 区域唯一标识
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 区域名称
     */
    public static final String COL_TITLE = "COL_TITLE";
    /**
     * 上级区域ID
     */
    public static final String COL_PARENT = "COL_PARENT";
    /**
     * 类型 1:省级、2:市级、3:区县级、4:街道
     */
    public static final String COL_LEVEL = "COL_LEVEL";
    /**
     * 查询关键字
     */
    public static final String COL_KEYWORD = "COL_KEYWORD";

    public static final int PROVINCE_LEVEL = 1;
    public static final int CITY_LEVEL = 2;
    public static final int DISTRICT_LEVEL = 3;
    public static final int STREET_LEVEL = 4;

    /**
     * 区域唯一标识
     */
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 区域名称
     */
    @Column(name = COL_TITLE, type = Column.Type.STRING)
    private String title;
    /**
     * 上级区域ID
     */
    @Column(name = COL_PARENT, type = Column.Type.STRING)
    private String parent;
    /**
     * 类型 1:省级、2:市级、3:区县级、4:街道
     */
    @Column(name = COL_LEVEL, type = Column.Type.INT)
    private Integer level;
    /**
     * 查询关键字
     */
    @Column(name = COL_KEYWORD, type = Column.Type.STRING)
    private String keyword;

}
