package com.adminpro.core.jdbc.sqlbuilder;

import com.adminpro.core.base.util.IdGenerator;
import com.adminpro.core.jdbc.utils.DbUtil;
import com.adminpro.core.tools.seq.SequenceService;
import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.List;

public class InsertBuilder {
    private String table;
    private StringBuilder columns;
    private StringBuilder markers;
    private List<Object> values;
    private String autoGeneratedKey;
    private String autoGeneratedType;
    private Object autoGeneratedValue;

    public InsertBuilder(String table) {
        this.table = table;
        columns = new StringBuilder();
        markers = new StringBuilder();
        values = new ArrayList<>();
    }

    public String getAutoGeneratedType() {
        return autoGeneratedType;
    }

    public void setAutoGeneratedType(String autoGeneratedType) {
        this.autoGeneratedType = autoGeneratedType;
    }

    public String getAutoGeneratedKey() {
        return autoGeneratedKey;
    }

    public void setAutoGeneratedKey(String autoGeneratedKey) {
        this.autoGeneratedKey = autoGeneratedKey;
        if (StringUtils.equals(this.autoGeneratedType, String.class.getName())) {
            String id = IdGenerator.getInstance().nextStringId();
            addColumnValue(autoGeneratedKey, id);
            setAutoGeneratedValue(id);
        } else {
            long id = SequenceService.getInstance().getNextLong("seq_" + this.table);
            addColumnValue(autoGeneratedKey, id);
            setAutoGeneratedValue(id);
        }
    }

    public Object getAutoGeneratedValue() {
        return autoGeneratedValue;
    }

    public void setAutoGeneratedValue(Object autoGeneratedValue) {
        this.autoGeneratedValue = autoGeneratedValue;
    }

    public void addColumnValue(String column, Object value) {
        columns.append(column).append(", ");
        markers.append("?, ");
        values.add(value);
    }

    public void addColumn(String column) {
        columns.append(column).append(", ");
        markers.append("?, ");
    }

    public void addValues(Object... objs) {
        values.add(objs);
    }

    public String getSql() {
        final StringBuilder sql = new StringBuilder();
        sql.append("INSERT INTO ");
        sql.append(table).append(" (");
        sql.append(columns.toString().substring(0, columns.lastIndexOf(", ")));
        //ID使用推特ID生成器，所以不需要这部分
        /*if (DbUtil.isSqlServer() && StringUtils.isNotBlank(autoGeneratedKey) && String.class.getName().equals(autoGeneratedType)) {
            sql.append(") OUTPUT INSERTED.").append(autoGeneratedKey).append(" VALUES (");
        } else {
            sql.append(") VALUES (");
        }*/
        sql.append(") VALUES (");
        sql.append(markers.toString().substring(0, markers.lastIndexOf(", ")));
        sql.append(')');
        return sql.toString();
    }

    @Override
    public String toString() {
        return getSql();
    }

    public Object[] getParamValues() {
        return values.toArray();
    }

    public List<Object> getValues() {
        return values;
    }
}
