package com.adminpro.rbac.domains.entity.domain;

import com.adminpro.core.base.entity.BaseEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 用户域环境配置表 sys_user_domain_env_tbl
 *
 * @author simon
 * @date 2018-09-06
 */
@Data
@Table(name = UserDomainEnvEntity.TABLE_NAME)
public class UserDomainEnvEntity extends BaseEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_DOMAIN_ENV_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 用户域基础角色
     */
    public static final String COL_COMMON_ROLE = "COL_COMMON_ROLE";
    /**
     * 用户域环境配置描述
     */
    public static final String COL_DESCRIPTION = "COL_DESCRIPTION";
    /**
     * 用户域公共错误页面url
     */
    public static final String COL_ERROR_PAGE_URL = "COL_ERROR_PAGE_URL";
    /**
     * 用户域严重错误页面url
     */
    public static final String COL_FATAL_ERROR_PAGE_URL = "COL_FATAL_ERROR_PAGE_URL";
    /**
     * 用户域首页页面url
     */
    public static final String COL_HOME_PAGE_URL = "COL_HOME_PAGE_URL";
    /**
     * 用户域布局名称
     */
    public static final String COL_LAYOUT = "COL_LAYOUT";
    /**
     * 用户域session过期页面url
     */
    public static final String COL_SESSION_EXPIRED_URL = "COL_SESSION_EXPIRED_URL";
    /**
     * 用户域
     */
    public static final String COL_USER_DOMAIN = "COL_USER_DOMAIN";

    public static final String COL_LOGIN_URL = "COL_LOGIN_URL";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 用户域基础角色
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_COMMON_ROLE, type = Column.Type.STRING)
    private String commonRole;
    /**
     * 用户域环境配置描述
     */
    @Column(name = COL_DESCRIPTION, type = Column.Type.STRING)
    private String description;
    /**
     * 用户域公共错误页面url
     */
    @Size(max = 255)
    @Column(name = COL_ERROR_PAGE_URL, type = Column.Type.STRING)
    private String errorPageUrl;
    /**
     * 用户域严重错误页面url
     */
    @Size(max = 255)
    @Column(name = COL_FATAL_ERROR_PAGE_URL, type = Column.Type.STRING)
    private String fatalErrorPageUrl;
    /**
     * 用户域首页页面url
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_HOME_PAGE_URL, type = Column.Type.STRING)
    private String homePageUrl;
    /**
     * 登录地址
     */
    @Size(max = 255)
    @Column(name = COL_LOGIN_URL, type = Column.Type.STRING)
    private String loginUrl;
    /**
     * 用户域布局名称
     */
    @Size(max = 255)
    @Column(name = COL_LAYOUT, type = Column.Type.STRING)
    private String layout;
    /**
     * 用户域session过期页面url
     */
    @Size(max = 255)
    @Column(name = COL_SESSION_EXPIRED_URL, type = Column.Type.STRING)
    private String sessionExpiredUrl;
    /**
     * 用户域
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_DOMAIN, type = Column.Type.STRING)
    private String userDomain;

}
