package com.adminpro.tools.domains.entity.dict;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.List;

/**
 * 字典类型表 sys_dict_tbl
 *
 * @author simon
 * @date 2020-05-21
 */
@Data
@Table(name = DictEntity.TABLE_NAME)
public class DictEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_DICT_TBL";

    /**
     * 字典主键
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 字典名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 字典键值
     */
    public static final String COL_KEY = "COL_KEY";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 备注
     */
    public static final String COL_REMARK = "COL_REMARK";

    /**
     * 字典主键
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 字典名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 字典键值
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_KEY, type = Column.Type.STRING)
    private String key;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 备注
     */
    @Size(max = 64)
    @Column(name = COL_REMARK, type = Column.Type.STRING)
    private String remark;

    private List<DictDataEntity> data;

}
