package com.adminpro.tools.domains.entity.dict;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * 字典数据表 sys_dict_data_tbl
 *
 * @author simon
 * @date 2020-05-21
 */
@Data
@Table(name = DictDataEntity.TABLE_NAME)
public class DictDataEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_DICT_DATA_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 字典类型
     */
    public static final String COL_KEY = "COL_KEY";
    /**
     * 排序
     */
    public static final String COL_ORDER = "COL_ORDER";
    /**
     * 标签
     */
    public static final String COL_LABEL = "COL_LABEL";
    /**
     * 键值
     */
    public static final String COL_VALUE = "COL_VALUE";
    /**
     * 样式属性
     */
    public static final String COL_CSS_CLASS = "COL_CSS_CLASS";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 字典类型
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_KEY, type = Column.Type.STRING)
    private String key;
    /**
     * 排序
     */
    @NotNull(message = "不能为空")
    @Column(name = COL_ORDER, type = Column.Type.INT)
    private Integer order;
    /**
     * 标签
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_LABEL, type = Column.Type.STRING)
    private String label;
    /**
     * 键值
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_VALUE, type = Column.Type.STRING)
    private String value;
    /**
     * 样式属性（其他样式扩展）
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_CSS_CLASS, type = Column.Type.STRING)
    private String cssClass;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;

}
