package com.adminpro.tools.domains.entity.config;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 参数配置表 sys_config_tbl
 *
 * @author simon
 * @date 2020-06-15
 */
@Data
@Table(name = ConfigEntity.TABLE_NAME)
public class ConfigEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_CONFIG_TBL";

    /**
     * 参数主键
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 参数键名
     */
    public static final String COL_KEY = "COL_KEY";
    /**
     * 参数名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 参数键值
     */
    public static final String COL_VALUE = "COL_VALUE";
    /**
     * 是否系统内置（Y是 N否）
     */
    public static final String COL_SYSTEM = "COL_SYSTEM";
    /**
     * 备注
     */
    public static final String COL_REMARK = "COL_REMARK";

    /**
     * 参数主键
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 参数键名
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_KEY, type = Column.Type.STRING)
    private String key;
    /**
     * 参数名称
     */
    @NotBlank
    @Size(max = 128)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 参数键值
     */
    @NotBlank
    @Size(max = 1024)
    @Column(name = COL_VALUE, type = Column.Type.STRING)
    private String value;
    /**
     * 是否系统内置（Y是 N否）
     */
    @Column(name = COL_SYSTEM, type = Column.Type.INT)
    private Integer system;
    /**
     * 备注
     */
    @Size(max = 500)
    @Column(name = COL_REMARK, type = Column.Type.STRING)
    private String remark;
}
