package com.adminpro.tools.domains.entity.oss;

import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import com.adminpro.framework.common.entity.BaseAuditEntity;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 文件上传表 sys_oss_tbl
 *
 * @author simon
 * @date 2018-09-06
 */
@Data
@Table(name = OSSEntity.TABLE_NAME)
public class OSSEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_OSS_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * URL地址
     */
    public static final String COL_URL = "COL_URL";
    /**
     * KEY
     */
    public static final String COL_KEY = "COL_KEY";
    /**
     * HASH
     */
    public static final String COL_HASH = "COL_HASH";
    /**
     * 后缀
     */
    public static final String COL_SUFFIX = "COL_SUFFIX";
    /**
     * 文件名字
     */
    public static final String COL_ORIGINAL = "COL_ORIGINAL";
    /**
     * 文件大小
     */
    public static final String COL_SIZE = "COL_SIZE";
    /**
     *
     */
    public static final String COL_BATCH_ID = "COL_BATCH_ID";
    /**
     *
     */
    public static final String COL_TYPE = "COL_TYPE";
    public static final String COL_STATUS = "COL_STATUS";
    /**
     *
     */
    public static final String COL_COVER = "COL_COVER";
    public static final String COL_COVER_KEY = "COL_COVER_KEY";

    public static final String TYPE_IMAGE = "image";
    public static final String TYPE_VIDEO = "video";
    public static final String TYPE_FILE = "file";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * URL地址
     */
    @NotBlank
    @Size(max = 200)
    @Column(name = COL_URL, type = Column.Type.STRING)
    private String url;
    /**
     * KEY
     */
    @NotBlank
    @Size(max = 200)
    @Column(name = COL_KEY, type = Column.Type.STRING)
    private String key;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * HASH
     */
    @NotBlank
    @Size(max = 200)
    @Column(name = COL_HASH, type = Column.Type.STRING)
    private String hash;
    /**
     * 后缀
     */
    @NotBlank
    @Size(max = 200)
    @Column(name = COL_SUFFIX, type = Column.Type.STRING)
    private String suffix;
    /**
     * 文件名字
     */
    @NotBlank
    @Size(max = 200)
    @Column(name = COL_ORIGINAL, type = Column.Type.STRING)
    private String original;
    /**
     * 文件大小
     */
    @Column(name = COL_SIZE, type = Column.Type.INT)
    private Integer size;
    /**
     *
     */
    @Size(max = 255)
    @Column(name = COL_BATCH_ID, type = Column.Type.STRING)
    private String batchId;
    /**
     *
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_TYPE, type = Column.Type.STRING)
    private String type;
    /**
     * 封面地址
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_COVER, type = Column.Type.STRING)
    private String cover;
    /**
     * 封面KEY
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_COVER_KEY, type = Column.Type.STRING)
    private String coverKey;
    /**
     * 其他附加属性
     */
    private String ext;

}
