package com.adminpro.rbac.domains.entity.post;

import com.adminpro.core.base.entity.BaseAuditEntity;
import com.adminpro.core.base.validator.IValidatorGroup;
import com.adminpro.core.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.core.jdbc.annotation.Column;
import com.adminpro.core.jdbc.annotation.PrimaryKey;
import com.adminpro.core.jdbc.annotation.Table;
import lombok.Data;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * 职位表 sys_post_tbl
 *
 * @author simon
 * @date 2020-05-21
 */
@Data
@Table(name = PostEntity.TABLE_NAME)
public class PostEntity extends BaseAuditEntity {
    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_POST_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * 职位编码
     */
    public static final String COL_CODE = "COL_CODE";
    /**
     * 职位名称
     */
    public static final String COL_NAME = "COL_NAME";
    /**
     * 显示顺序
     */
    public static final String COL_SORT = "COL_SORT";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 备注
     */
    public static final String COL_REMARK = "COL_REMARK";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * 职位编码
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_CODE, type = Column.Type.STRING)
    private String code;
    /**
     * 职位名称
     */
    @NotBlank
    @Size(max = 50)
    @Column(name = COL_NAME, type = Column.Type.STRING)
    private String name;
    /**
     * 显示顺序
     */
    @Column(name = COL_SORT, type = Column.Type.INT)
    private Integer sort;
    /**
     * 状态
     */
    @NotBlank
    @Size(max = 20)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 备注
     */
    @Size(max = 500)
    @Column(name = COL_REMARK, type = Column.Type.STRING)
    private String remark;
}
