package com.adminpro.system.rbac.domains.entity.usertoken;

import com.adminpro.framework.base.entity.BaseEntity;
import com.adminpro.framework.base.validator.IValidatorGroup;
import com.adminpro.framework.jdbc.annotation.AutoGeneratedKey;
import com.adminpro.framework.jdbc.annotation.Column;
import com.adminpro.framework.jdbc.annotation.PrimaryKey;
import com.adminpro.framework.jdbc.annotation.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;
import org.apache.commons.lang3.StringUtils;

import java.util.Date;

/**
 * 用户Token实体类
 * <p>
 * 该实体对应系统用户Token表(SYS_USER_TOKEN_TBL)，用于存储用户的登录令牌信息。
 * Token是无状态认证机制的核心，用于在前后端分离架构中维持用户的登录状态。
 * </p>
 * <p>
 * 主要功能包括：
 * <ul>
 * <li>Token基本信息：Token值、关联的用户ID等</li>
 * <li>Token有效期管理：过期时间控制，支持Token自动续期</li>
 * <li>Token状态管理：活动状态、非活动状态</li>
 * <li>设备信息管理：记录登录设备信息，支持多端登录控制</li>
 * <li>Token校验：通过isValid()方法校验Token是否有效</li>
 * </ul>
 * </p>
 * <p>
 * Token有效性判断标准：
 * <ul>
 * <li>状态为活动状态(STATUS_ACTIVITY)</li>
 * <li>未超过过期时间</li>
 * </ul>
 * </p>
 * <p>
 * 继承自BaseEntity，包含基础的创建时间等字段。
 * 使用Lombok的@Data注解自动生成getter/setter、toString、equals、hashCode等方法。
 * </p>
 *
 * @author simon
 * @date 2018-09-03
 * @see com.adminpro.framework.base.entity.BaseEntity
 */
@Data
@Table(name = UserTokenEntity.TABLE_NAME)
public class UserTokenEntity extends BaseEntity {

    /**
     * Token活动状态标识
     */
    public static final String STATUS_ACTIVITY = "activity";
    /**
     * Token非活动状态标识
     */
    public static final String STATUS_INACTIVITY = "inactivity";

    private static final long serialVersionUID = 1L;
    /**
     * 表名
     */
    public static final String TABLE_NAME = "SYS_USER_TOKEN_TBL";

    /**
     * ID
     */
    public static final String COL_ID = "COL_ID";
    /**
     * Token值
     */
    public static final String COL_TOKEN = "COL_TOKEN";
    /**
     * 用户ID
     */
    public static final String COL_USER_ID = "COL_USER_ID";

    /**
     * 登录设备
     */
    public static final String COL_DEVICE = "COL_DEVICE";
    /**
     * 过期时间
     */
    public static final String COL_EXPIRE_TIME = "COL_EXPIRE_TIME";
    /**
     * 状态
     */
    public static final String COL_STATUS = "COL_STATUS";
    /**
     * 更新时间
     */
    public static final String COL_UPDATE_TIME = "COL_UPDATE_TIME";

    /**
     * ID
     */
    @NotBlank(groups = IValidatorGroup.Update.class)
    @Size(max = 64)
    @AutoGeneratedKey
    @PrimaryKey
    @Column(name = COL_ID, type = Column.Type.STRING)
    private String id;
    /**
     * Token值
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = COL_TOKEN, type = Column.Type.STRING)
    private String token;
    /**
     * 用户ID
     */
    @NotBlank
    @Size(max = 64)
    @Column(name = COL_USER_ID, type = Column.Type.STRING)
    private String userId;

    /**
     * 登录设备
     */
    @Size(max = 255)
    @Column(name = COL_DEVICE, type = Column.Type.STRING)
    private String device;
    /**
     * 过期时间
     */
    @Column(name = COL_EXPIRE_TIME, type = Column.Type.DATETIME)
    private Date expireTime;
    /**
     * 状态
     */
    @Size(max = 64)
    @Column(name = COL_STATUS, type = Column.Type.STRING)
    private String status;
    /**
     * 更新时间
     */
    @Column(name = COL_UPDATE_TIME, type = Column.Type.DATETIME)
    private Date updateTime;

    /**
     * 校验Token是否有效
     * <p>
     * Token有效的条件：
     * <ul>
     * <li>Token状态为活动状态(STATUS_ACTIVITY)</li>
     * <li>当前时间未超过Token的过期时间</li>
     * </ul>
     * </p>
     * <p>
     * 该方法使用@JsonIgnore注解，在序列化为JSON时会被忽略，
     * 避免Token信息在API响应中泄露。
     * </p>
     *
     * @return 如果Token有效返回true，否则返回false
     */
    @JsonIgnore
    public boolean isValid() {
        return StringUtils.equals(getStatus(), STATUS_ACTIVITY) && !expireTime.before(new Date());
    }
}
